---
deployment:
  tasks:
    - cp /home/levanpms/elite-message.env /home/levanpms/repositories/EliteMessage/.env
    - corepack enable
    - corepack prepare pnpm@10.33.0 --activate
    - pnpm install --frozen-lockfile
    - pnpm build
    - rm -f /home/levanpms/repositories/EliteMessage/.env
